site_name: Taha Kiziltepe
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Articles: articles.md
  - Videos: videos.md
theme:
  name: material
  icon:
    logo: material/brush
    favicon: material/brush
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tahakiziltepe/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mtahakiziltepe/
