site_name: My docs
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono